config/routes.rb
Rails.application.routes.draw do
  

  resources :course_types, only: [:index,:new, :show, :update, :edit] do
    resources :courses  
  end

  post 'course_types' => 'course_types#create'
  get '/signup' => 'learners#new'

  post '/signup' => 'learners#create'

  get 'course_types' => 'course_types#index'
 
  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

  root 'sessions#new'
  

end

app/models/course.rb
class Course < ActiveRecord::Base
    has_one :course_type
    #has_many :learners, through: :registrations
end

app/models/course_type.rb
class CourseType < ActiveRecord::Base
    has_many :courses
end

app/models/learner.rb
class Learner < ActiveRecord::Base
    has_many :courses, through: :registrations
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user
  
  def current_user
    @current_user ||= Learner.find(session[:user_id]) if session[:user_id]
  end
  
  def require_user
    redirect_to '/login' unless current_user
  end
  
end

app/controllers/course_types_controller.rb
class CourseTypesController < ApplicationController
  before_action :require_user
  
  def index
    @courseTypes = CourseType.all
  end

  def new
    @courseType = CourseType.new
  end

  def create
    @courseType = CourseType.new(courseTypeParams)
    
    if @courseType.save
      redirect_to course_types_path
    else
      redirect_to new_course_type_path
    end
  end

  def edit
    @courseType = CourseType.find_by_id(params[:id])
  end
  
  def update
    @courseType = CourseType.find(params[:id])
    if @courseType.update_attributes(courseTypeParams)
      redirect_to "/course_types"
    else
      redirect_to root_url
    end
    
  end
  
  def show
    @courseType = CourseType.find(params[:id])
  end
  
  private
  
  def courseTypeParams
    params.require(:course_type).permit(:description,:name,:is_active)
  end
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  
  def index
    @courseType = CourseType.find(params[:course_type_id])
    @courses = @courseType.courses
  end
  
  
  def new
    @course = Course.new
    @courseTypes = CourseType.find(params[:course_type_id])
  end

  def show
    @course = Course.find(params[:id])
  end

  def edit
    @courseType = CourseType.find(params[:course_type_id])
    @course = Course.find(params[:id])
  end
  
  def create
    @course = Course.new(courseParams)
    if @course.save 
      redirect_to "/course_types"
    else
      redirect_to root_url
    end
  end
  
  private
  
  def courseParams
    params.require(:course).permit(:start, :end, :course_type_id)
  end
  
  
end

app/controllers/learners_controller.rb
class LearnersController < ApplicationController
  def new
    @learner = Learner.new
  end

  def create
    @learner = Learner.new(learner_params)
    if @learner.save
      session[:user_id] = @learner.id
      redirect_to course_types_path
    else
      redirect_to signup_url
    end
  end
  
  private
  
  def learner_params
     params.require(:learner).permit(:first_name, :last_name, :email, :password, :password_confirmation) 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to course_types_path if current_user
  end

  def create
    learner = Learner.find_by_email(params[:session][:email])
    if learner && learner.authenticate(params[:session][:password])
      session[:user_id] = learner.id
      redirect_to course_types_path
    else
      redirect_to login_url
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_types_helper.rb
module CourseTypesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/learners_helper.rb
module LearnersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/course_types/_form.html.erb
<%= form_for @courseType do |f| %>
<P><%= f.text_field :name, :placeholder => "Course Title" %></P>
<P><%= f.text_area :description, :placeholder => "Description" %> </P>
<P><%= f.submit :class => "btn btn-primary"%></P>

<% end %>

app/views/course_types/edit.html.erb
<h1>Edit Course Type</h1>

<%= render "form" %>

app/views/course_types/index.html.erb
<h1>Course Types</h1>

<table class="table table-striped table-hover table-responsive">
    <thead>
    <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Actions</th>
            
    </tr>
    </thead>
    <% @courseTypes.each do |courseType| %>
        <tr>
            <td><%=courseType.name %></td>
            <td><%=courseType.description %></td>
            <td><a href=<%=course_type_path(courseType.id)%> class="btn btn-default">
                <span class="glyphicon glyphicon-search"></span></a>
            <a href=<%=edit_course_type_path(courseType.id)%> 
            class="btn btn-default"><span class='glyphicon glyphicon-plus'></span></a>
            <a href=<%=edit_course_type_path(courseType.id)%> 
            class="btn btn-default"><span class='glyphicon glyphicon-pencil'></span></a></td>
            
        </tr>
    <% end %>
</table>

app/views/course_types/new.html.erb
<h1>Create New Course Type</h1>

<%= render "form" %>

app/views/course_types/show.html.erb
<h1><%= @courseType.name %></h1>


<div class="xs-col-12" >
    <%= @courseType.description %>
</div>
<h3>Courses</h3>
<table class="table table-striped table-hover table-responsive">
    <thead>
        <tr>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Actions</th>
        </tr>
        
    </thead>
    <% @courseType.courses.each do |course| %>
    <tr>
        <td><%= course.start.to_s(:course) %></td>
        <td><%= course.end.to_s(:course) %></td>
        <td><a href=<%= edit_course_path(course.id)%> class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span></a> </td>
    </tr>
    
    <% end %>
</table>

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>

<P><%=f.label "Start Date and Time:" %><%= f.datetime_select :start %></p>

<p><%=f.label "End Date and Time:"%><%= f.datetime_select :end %></p>


<%= f.submit :class => "form-btn" %>

<% end %>

app/views/courses/edit.html.erb
<H1>Edit Course <%=@course.id%> for CourseType <%=@courseType.id%></H1>

app/views/courses/index.html.erb
Courses Index for Course Type for: <%= params[:course_type_id] %>

app/views/courses/new.html.erb
<h1>Create New Course</h1>

app/views/courses/show.html.erb
<h1>Courses#show</h1>
<p>Find me in app/views/courses/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %> 
          <li><%=link_to "Home", "#"%></li>
          <li><%=link_to "Log out", logout_path, method: "delete" %></li>
          <P class="navbar-text">Signed in as <%= "#{current_user.first_name} #{current_user.last_name}" %> </P>
        <% else %>
        <li><%=link_to "Sign up", signup_path %></li>
        <li><%=link_to "Log in", "#"%></li>
        <% end %>
      </ul>
      
    </nav>
    
  </div>
</header>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/learners/new.html.erb
<h1>Sign Up</h1>

<%=form_for :learner do |f| %>
<P><%= f.text_field :first_name, :placeholder => "First Name" %>
<P><%= f.text_field :last_name, :placeholder => "Last Name" %>
<P><%= f.text_field :email, :placeholder => "E-mail" %>
<P><%= f.password_field :password, :placeholder => "Password" %>
<P><%= f.password_field :password_confirmation, :placeholder => "Confirm Password" %>
<P><%= f.submit "Sign Up", :class => "btn btn-primary"%>


<% end %>